name: Build and Release WPF App

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package WPF App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Adjust for your .NET version

      - name: Get Version from .csproj
        id: get_version
        run: |
          $version = [xml](Get-Content ./AudioSplitter/AudioSplitter.csproj)
          $version = $version.Project.PropertyGroup.Version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Install WiX Toolset
        run: choco install wixtoolset --yes

      - name: Build MSI Installer
        run: |
          candle Product.wxs
          light -out AudioSplitter-${{ env.VERSION }}.msi Product.wixobj

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioSplitter-${{ env.VERSION }}.msi
          path: ./AudioSplitter-${{ env.VERSION }}.msi

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download MSI Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./

      - name: Rename Artifact
        run: mv ./AudioSplitter-${{ env.VERSION }}.msi/artifact.msi ./AudioSplitter-${{ env.VERSION }}.msi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AudioSplitter-${{ env.VERSION }}.msi
          tag_name: v${{ env.VERSION }}
          release_name: "Release v${{ env.VERSION }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GH_PAT }}
