name: Build and Release WPF App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test WPF App
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Adjust for your .NET version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal

      - name: Archive Build
        run: Compress-Archive -Path ./publish/* -DestinationPath ./release.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WPF-App-Build
          path: ./release.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: WPF-App-Build
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release.zip
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
