name: Build and Release Portable WPF App

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package Portable WPF App
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust for your .NET version

      - name: Get Version from .csproj
        id: get_version
        run: |
          $version = [xml](Get-Content ./AudioSplitter.UI/AudioSplitter.UI.csproj)
          $version = $version.Project.PropertyGroup.Version
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Generate Inno Setup Script for Portable Installation
        run: |
          @'
          [Setup]
          AppName=Audio Sample Splitter
          AppVersion=${{ steps.get_version.outputs.version }}
          PrivilegesRequired=lowest
          DefaultDirName={userappdata}\Audio Sample Splitter
          DefaultGroupName=Audio Sample Splitter
          OutputDir=.
          OutputBaseFilename=AudioSplitterPortableSetup
          Compression=lzma2
          SolidCompression=yes
          ArchitecturesInstallIn64BitMode=x64
          
          [Files]
          Source: "publish\*"; DestDir: "{app}"; Flags: recursesubdirs
          
          [Icons]
          Name: "{group}\Audio Sample Splitter"; Filename: "{app}\AudioSplitter.UI.exe"
          
          [Run]
          Filename: "{app}\AudioSplitter.UI.exe"; Description: "Launch the application"; Flags: nowait postinstall skipifsilent
          '@ | Out-File -FilePath installer.iss -Encoding utf8

      - name: Build Installer
        run: iscc installer.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudioSplitterPortableSetup.exe
          path: ./AudioSplitterPortableSetup.exe

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Installer Artifact
        uses: actions/download-artifact@v4
        with:
          name: AudioSplitterPortableSetup.exe
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: AudioSplitterPortableSetup.exe
          tag_name: v${{ needs.build.outputs.version }}
          release_name: "Release v${{ needs.build.outputs.version }}"
          draft: false
          prerelease: false
          token: ${{ secrets.GH_PAT }}
